# Starter pipeline for Python in Azure DevOps

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:


# Use a Python version
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

# Install dependencies (if requirements.txt exists)
- script: |
    if [ -f requirements.txt ]; then
      pip install -r requirements.txt
    fi
  displayName: 'Install Python dependencies'

# Run a one-line script
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Run a Python script
- script: |
    python hello.py
  displayName: 'Run hello.py'

